Vagrant.configure("2") do |config|
  config.vm.define "mysql-server" do |vm|
    vm.vm.box = "bento/ubuntu-23.10"
    vm.vm.hostname = "mysql-server"
    vm.vm.network "public_network"
    vm.vm.provision "shell", path: "./scripts/install.sh"


  end

end