Vagrant.configure("2") do |config|
  config.vm.define "webserver" do |vm|
    vm.vm.box = "bento/ubuntu-24.04"
    vm.vm.hostname = "webserver-01"
    vm.vm.network = "public_network"
    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    vm.vm.synced_folder "Lecture_4/SharedFolder", "/home/user/shared"
  end
end