Vagrant.configure("2") do |config|
  config.vm.define "webserver-01" do |vm|
    vm.vm.box = "bento/ubuntu-23.10"
    vm.vm.hostname = "webserver-01"
    vm.vm.network "public_network"
    vm.vm.provision "shell", path: "./scripts/install.sh"

  end

end