Vagrant.configure("2") do |config|

  (1..3).each do |i|
    config.vm.define "webserver-#{0 +  i}" do |vm|
      vm.vm.box = "bento/ubuntu-22.04"
      vm.vm.hostname = "webserver-#{0 + i}"
      vm.vm.network "private_network", ip: "192.168.56.#{10 + i}"
      vm.vm.synced_folder "./SharedFolder", "/shared"
      vm.vm.provision "shell", path: "./scripts/install.sh"

    end
  end

end